name: "TODO to Issue"
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.4
        id: todo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMENT_MARKER: "#"
          CLOSE_ISSUES: true
          AUTO_P: true
          AUTO_ASSIGN: true
          LABEL: "todo"
      - name: Debug Info
        run: |
          echo "Found TODOs: ${{ steps.todo.outputs.number_of_todos }}"